# Site settings
title: "Joe Palala's blog"
name: "Joe's blog"
url: "http://jpalala.github.io"
email: jose.palala@live.com
description: blog.jpalala.com
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username:  jpalala # Twitter ID
github_username:  jpalala # Github ID
# google-analytics_id: UA-50593531-1  # Google Analytics ID
rss_url: "/feed.xml"  # RSS
logo_image: "/images/logo.png"  # LOGO

# Build settings
gems: [jekyll-paginate]
markdown: rdiscount
highlighter: pygments
permalink: /:title/
paginate: 8
paginate_path: page/:num
GH_ENV: gh_pages
